"""empty message

Revision ID: c2401cdb5c62
Revises: 7c949fda9de1
Create Date: 2021-11-04 16:38:45.162945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2401cdb5c62'
down_revision = '7c949fda9de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.drop_table('books_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genres',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='books_genres_book_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='books_genres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name='books_genres_pkey')
    )
    op.drop_table('books_genre')
    # ### end Alembic commands ###
